services:
  dms-backend:
    build:
      context: ./dms-backend
      dockerfile: dev.dockerfile
      args:
        UID: 1000
        GID: 1000
    ports:
      - 9229:9229
      - 3500:3500
    volumes:
      - ./dms-backend/settings.d:/etc/dms.d
      - ./dms-backend/settings:/etc/dms
      - ./dms-backend/src:/dms/src
      - ./dms-backend/package.json:/dms/package.json
      - ./dms-backend/package-lock.json:/dms/package-lock.json

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Qwerty1!
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9090:9090
    command: ["server", "/data", "--console-address", ":9090"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty1!
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  minio:
  postgres: