services:
  dms-backend:
    build:
      context: ./dms-backend
      dockerfile: dev.dockerfile
      args:
        UID: 1000
        GID: 1000
    ports:
      - 9229:9229
      - 3500:3500
    volumes:
      - ./dms-backend/settings.d:/etc/dms.d
      - ./dms-backend/src:/dms/src

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Qwerty1!
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9090:9090
    command: ["server", "/data", "--console-address", ":9090"]

volumes:
  minio:
